INSERT INTO `recipes` (`id`, `id_prod`, `ingredient`, `amount`, `imagem`) VALUES (NULL, '23', 'Manga', 'Inteira Madura ', 'Mango.png'), 
(NULL, '23', 'Abacaxi', '1/2 Médio', 'Pineapple.png'), 
(NULL, '23', 'Laranja', '3 grandes', 'Orange.png'), 
(NULL, '23', 'Limão', '2 Grandes', 'Lemon.png'), 
(NULL, '23', 'Água', '200ml', 'Water.png'), 
(NULL, '23', 'Açúcar', 'a gosto', 'Sugar.png'), 
(NULL, '23', 'Gelo', 'opcional', 'Ice.png'), 
(NULL, '24', 'Maracujá', '2 Médios', 'Passionfruit.png'), 
(NULL, '24', 'Abacaxi', '1/2 Cerca de 300g', 'Pineapple.png'), 
(NULL, '24', 'Água', '1 litro', 'Water.png'), 
(NULL, '24', 'Açúcar', 'a gosto', 'Sugar.png'), 
(NULL, '24', 'Gelo', 'opcional', 'Ice.png'), 
(NULL, '25', 'Pêssego', '3 Médios 450g', 'Peaches.png'), 
(NULL, '25', 'Água', '500ml', 'Water.png'), 
(NULL, '25', 'Açúcar', 'a gosto', 'Sugar.png'), 
(NULL, '25', 'Gelo', 'opcional', 'Ice.png'), 
(NULL, '25', 'Morango', '1 xícara de chá', 'Strawberry.png'), 
(NULL, '25', 'Framboesas', '1/2 Xícara de Chá', 'Raspberry.png'), 
(NULL, '25', 'Amoras', '1/2 Xícara de chá', 'Blackberry.png'), 
(NULL, '25', 'Mirtilo', '1/2 Xícara de Chá', 'Blueberry.png'), 
(NULL, '25', 'Água', '500ml', 'Water.png'), 
(NULL, '25', 'Açúcar', 'a gosto', 'Sugar.png'), 
(NULL, '25', 'Gelo', 'opcional', 'Ice.png'), 
(NULL, '26', 'Chá de Erva Doce', '1 litro', 'FennelTea.png'), 
(NULL, '26', 'Suco de Limão', '1 Xícara de Chá', 'Lemon.png'), 
(NULL, '26', 'Açúcar', 'a gosto', 'Sugar.png'), 
(NULL, '26', 'Gelo', 'opcional', 'Ice.png'), 
(NULL, '27', 'Uvas Verdes', '500g ', 'Grape.png'), 
(NULL, '27', 'Kiwis', '5 médios cerca de 390g', 'Kiwi.png'), 
(NULL, '27', 'Hortelã', '15 folhas', 'Mint.png'), 
(NULL, '27', 'Água', '600ml', 'Water.png'), 
(NULL, '27', 'Açúcar', 'a gosto', 'Sugar.png'), 
(NULL, '27', 'Gelo', 'opcional', 'Ice.png'), 
(NULL, '28', 'Amoras ', '3 xícaras de chá', 'Blackberry.png'), 
(NULL, '28', 'Limão', '2 limões', 'Lemon.png'), 
(NULL, '', 'Hortelã', 'Decorar', 'Mint.png'), 
(NULL, '28', 'Água', '600ml', 'Water.png'), 
(NULL, '28', 'Açúcar', 'a gosto', 'Sugar.png'), 
(NULL, '28', 'Gelo', 'opcional', 'Ice.png'), 
(NULL, '29', 'Limão', '1/2 Xícara de Chá', 'Lemon.png'), 
(NULL, '29', 'Água', '960ml', 'Water.png'), 
(NULL, '29', 'Framboesa', '1/2 Xícara de Chá', 'Raspberry.png'), 
(NULL, '29', 'Açúcar', 'a gosto', 'Sugar.png'), 
(NULL, '29', 'Gelo', 'opcional', 'Ice.png'), 
(NULL, '30', 'Pitaya', '1 Grande', 'Dragonfruit.png'), 
(NULL, '30', 'Limão', '3 Limões', 'Lemon.png'), 
(NULL, '30', 'Água', '1 litro', 'Water.png')