const DrinksData = [
    {
      id: 1,
      image: require("../assets/images/Drinks/Caipirinha.png"),
      characteristic: "Caipirinha",
      icon: require("../assets/images/HeartNaked.png"),
    },
    {
      id: 2,
      image: require("../assets/images/Drinks/MoscowMule.png"),
      characteristic: "Moscow Mule",
      icon: require("../assets/images/HeartNaked.png"),
    },
    {
      id: 3,
      image: require("../assets/images/Drinks/Sangria.png"),
      characteristic: "Sangria",
      icon: require("../assets/images/HeartNaked.png"),
    },
    {
      id: 4,
      image: require("../assets/images/Drinks/Margarita.png"),
      characteristic: "Margarita",
      icon: require("../assets/images/HeartNaked.png"),
    },
    {
      id: 5,
      image: require("../assets/images/Drinks/VirginOnTheBeach.png"),
      characteristic: "Virgin On The Beach",
      icon: require("../assets/images/HeartNaked.png"),
    },
    {
      id: 6,
      image: require("../assets/images/Drinks/Mojito.png"),
      characteristic: "Mojito",
      icon: require("../assets/images/HeartNaked.png"),
    },
    {
      id: 7,
      image: require("../assets/images/Drinks/PinaColada.png"),
      characteristic: "Pina Colada",
      icon: require("../assets/images/HeartNaked.png"),
    },
    {
      id: 8,
      image: require("../assets/images/Drinks/BlueHawaiian.png"),
      characteristic: "Blue Hawaiian",
      icon: require("../assets/images/HeartNaked.png"),
    },
    {
      id: 9,
      image: require("../assets/images/Drinks/Flower.png"),
      characteristic: "Flower",
      icon: require("../assets/images/HeartNaked.png"),
    },
    {
      id: 10,
      image: require("../assets/images/Drinks/MelanciaFizz.png"),
      characteristic: "Melancia Fizz",
      icon: require("../assets/images/HeartNaked.png"),
    },
    {
      id: 11,
      image: require("../assets/images/Coffes/Capuccino.png"),
      characteristic: "Capuccino",
      icon: require("../assets/images/HeartNaked.png"),
    },
    {
      id: 12,
      image: require("../assets/images/Coffes/Affogato.png"),
      characteristic: "Affogato",
      icon: require("../assets/images/HeartNaked.png"),
    },
    {
      id: 13,
      image: require("../assets/images/Coffes/Mochaccino.png"),
      characteristic: "Mochaccino",
      icon: require("../assets/images/HeartNaked.png"),
    },
    {
      id: 14,
      image: require("../assets/images/Coffes/Machiatto.png"),
      characteristic: "Machiatto",
      icon: require("../assets/images/HeartNaked.png"),
    },
    {
      id: 15,
      image: require("../assets/images/Coffes/Latte.png"),
      characteristic: "Latte",
      icon: require("../assets/images/HeartNaked.png"),
    },
    {
      id: 16,
      image: require("../assets/images/Coffes/Frappe.png"),
      characteristic: "Frappe",
      icon: require("../assets/images/HeartNaked.png"),
    },
    {
      id: 17,
      image: require("../assets/images/Coffes/Smoothie.png"),
      characteristic: "Smoothie",
      icon: require("../assets/images/HeartNaked.png"),
    },
    {
      id: 18,
      image: require("../assets/images/Coffes/IcedMocha.png"),
      characteristic: "Mocha Gelado",
      icon: require("../assets/images/HeartNaked.png"),
    },
    {
      id: 19,
      image: require("../assets/images/Coffes/Coffe.png"),
      characteristic: "Café",
      icon: require("../assets/images/HeartNaked.png"),
    },
    {
      id: 20,
      image: require("../assets/images/Coffes/IcedCoffe.png"),
      characteristic: "Café Gelado",
      icon: require("../assets/images/HeartNaked.png"),
    },
    {
      id: 21,
      image: require("../assets/images/Juices/GreenJuice.png"),
      characteristic: "Suco Verde",
      icon: require("../assets/images/HeartNaked.png"),
    },
    {
      id: 22,
      image: require("../assets/images/Juices/OrangeCarrotJuice.png"),
      characteristic: "Suco de Laranja com Cenoura",
      icon: require("../assets/images/HeartNaked.png"),
    },
    {
      id: 23,
      image: require("../assets/images/Juices/TropicalJuice.png"),
      characteristic: "Suco Tropical",
      icon: require("../assets/images/HeartNaked.png"),
    },
    {
      id: 24,
      image: require("../assets/images/Juices/PineapplePassionJuice.png"),
      characteristic: "Suco de Abacaxi com Maracujá",
      icon: require("../assets/images/HeartNaked.png"),
    },
    {
      id: 25,
      image: require("../assets/images/Juices/MangoRedJuice.png"),
      characteristic: "Suco de Vermelhas com Manga",
      icon: require("../assets/images/HeartNaked.png"),
    },
    {
      id: 26,
      image: require("../assets/images/Juices/LemonTeaJuice.png"),
      characteristic: "Suco de Limão com Chá",
      icon: require("../assets/images/HeartNaked.png"),
    },
    {
      id: 27,
      image: require("../assets/images/Juices/GrapeKiwiJuice.png"),
      characteristic: "Suco de Kiwi com Uva",
      icon: require("../assets/images/HeartNaked.png"),
    },
    {
      id: 28,
      image: require("../assets/images/Juices/LemonBlackbarryJuice.png"),
      characteristic: "Suco de Limão com Amora",
      icon: require("../assets/images/HeartNaked.png"),
    },
    {
      id: 29,
      image: require("../assets/images/Juices/PinkLemonJuice.png"),
      characteristic: "Pink Limonade",
      icon: require("../assets/images/HeartNaked.png"),
    },
    {
      id: 30,
      image: require("../assets/images/Juices/DragonJuice.png"),
      characteristic: "Suco de Pitaia",
      icon: require("../assets/images/HeartNaked.png"),
    },
  ];

  export default DrinksData;